# Generated by Django 3.2.9 on 2021-12-05 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_ordermvto_cant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('consecutive', models.IntegerField(verbose_name='Consecutivo')),
                ('status', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Despachado', 'Despachado'), ('Recibido', 'Recibido')], default='Nuevo', max_length=25, null=True, verbose_name='Estado')),
                ('shipment_date', models.DateTimeField(verbose_name='Fecha Despacho')),
                ('received_date', models.DateTimeField(verbose_name='Fecha Recibido')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
