# Generated by Django 3.2.9 on 2021-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_consecutive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='received_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Recibido'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Despacho'),
        ),
    ]
