# Generated by Django 3.2.9 on 2021-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20211205_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='received_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_notification',
            field=models.BooleanField(default=False),
        ),
    ]
