# Generated by Django 3.2.9 on 2021-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211205_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado')], default='Nuevo', max_length=25, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordermvto',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ordermvto',
            name='cant',
            field=models.FloatField(blank=True, default=1, verbose_name='Cantiddad'),
        ),
    ]
