# Generated by Django 3.2.9 on 2021-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211205_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermvto',
            name='cant',
            field=models.FloatField(blank=True, default=1, verbose_name='Cantidad'),
        ),
    ]
